# Welcome to Jekyll!
#
# This config file is for settings that affect your entire site.
# For technical reasons, this file is *NOT* reloaded automatically when you use `jekyll serve`.

# Site settings
title: 杨建江的学术网站
description: 展示我的研究方向：大语言模型
baseurl: ""  # leave this empty
url: "https://Yjj-109.github.io"  # 你的 GitHub Pages 地址

author:
  name: 杨建江
  email: Edisonyang109@outlook.com

# Minimal Mistakes theme settings
remote_theme: "mmistakes/minimal-mistakes"

# Choose your theme skin
minimal_mistakes_skin: "default"  # 可以选择 "air", "contrast", "dark", "neon", "plum", "sunrise"

# Language settings
locale: "en-US"

# Social Links (你可以在此处添加更多链接)
github: Yjj-109
email: Edisonyang109@outlook.com

# Plugins (do not remove)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "single"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag

